
data = {
    "Adamantium Ore": [ "Restore Magicka", "Reflect", "Burden", "Poison" ],
    "Alit Hide": [ "Telekinesis", "Detect Animal", "Resist Poison", "Drain Intelligence" ],
    "Ampoule Pod": [ "Water Walking", "Detect Animal", "Drain Willpower", "Paralyze" ],
    "Ash Salts": [ "Cure Blight Disease", "Resist Magicka", "Drain Agility" ],
    "Ash Yam": [ "Detect Key", "Fortify Intelligence", "Fortify Strength", "Resist Common Disease" ],
    "Bear Pelt": [ "Night Eye", "Fortify Strength", "Resist Common Disease", "Drain Fatigue" ],
    "Belladonna Berries": [ "Restore Magicka", "Fortify Magicka", "Resist Magicka", "Drain Magicka" ],
    "Bittergreen Petals": [ "Restore Intelligence", "Invisibility", "Drain Magicka", "Drain Endurance" ],
    "Black Anther": [ "Light", "Resist Fire", "Drain Agility", "Drain Endurance" ],
    "Black Lichen": [ "Cure Poison", "Resist Frost", "Drain Speed", "Drain Strength" ],
    "Bloat": [ "Detect Animal", "Fortify Intelligence", "Fortify Willpower", "Drain Magicka" ],
    "Bonemeal": [ "Restore Agility", "Telekinesis", "Drain Fatigue", "Drain Personality" ],
    "Bread": [ "Restore Fatigue" ],
    "Bristleback Leather": [ "Recall", "Resist Frost", "Blind", "Frost Damage" ],
    "Bungler's Bane": [ "Dispel", "Drain Endurance", "Drain Speed", "Drain Strength" ],
    "Chokeweed": [ "Restore Fatigue", "Cure Common Disease", "Drain Luck", "Drain Willpower" ],
    "Coda Flower": [ "Levitate", "Drain Health", "Drain Intelligence", "Drain Personality" ],
    "Comberry": [ "Restore Magicka", "Fire Shield", "Reflect", "Drain Fatigue" ],
    "Corkbulb Root": [ "Restore Health", "Lightning Shield", "Cure Paralyzation", "Fortify Luck" ],
    "Corprus Weepings": [ "Restore Health", "Fortify Luck", "Drain Fatigue", "Drain Willpower" ],
    "Crab Meat": [ "Restore Fatigue", "Restore Luck", "Lightning Shield", "Resist Shock" ],
    "Daedra Skin": [ "Swift Swim", "Cure Common Disease", "Fortify Strength", "Paralyze" ],
    "Daedra's Heart": [ "Restore Magicka", "Night Eye", "Fortify Endurance", "Drain Agility" ],
    "Diamond": [ "Invisibility", "Detect Key", "Reflect", "Drain Agility" ],
    "Dreugh Wax": [ "Restore Strength", "Fortify Strength", "Drain Luck", "Drain Willpower" ],
    "Durzog Meat": [ "Fortify Agility", "Fortify Strength", "Blind", "Damage Magicka" ],
    "Ectoplasm": [ "Detect Animal", "Fortify Agility", "Drain Health", "Drain Strength" ],
    "Emerald": [ "Restore Health", "Fortify Magicka", "Drain Agility", "Drain Endurance" ],
    "Fire Petal": [ "Spell Absorption", "Resist Fire", "Drain Health", "Paralyze" ],
    "Fire Salts": [ "Fire Shield", "Fortify Agility", "Resist Frost", "Drain Health" ],
    "Frost Salts": [ "Restore Magicka", "Frost Shield", "Resist Fire", "Drain Speed" ],
    "Ghoul Heart": [ "Cure Poison", "Fortify Attack", "Paralyze" ],
    "Gold Kanet": [ "Restore Strength", "Drain Health", "Drain Luck", "Burden" ],
    "Golden Sedge Flowers": [ "Swift Swim", "Fortify Attack", "Fortify Strength", "Drain Magicka" ],
    "Grahl Eyeball": [ "Night Eye", "Fortify Strength", "Resist Frost", "Drain Magicka" ],
    "Gravedust": [ "Restore Endurance", "Cure Common Disease", "Drain Magicka", "Drain Intelligence" ],
    "Gravetar": [ "Fortify Fatigue", "Resist Frost", "Drain Health", "Drain Luck" ],
    "Green Lichen": [ "Cure Common Disease", "Fortify Personality", "Drain Health", "Drain Strength" ],
    "Guar Hide": [ "Restore Personality", "Fortify Endurance", "Fortify Luck", "Drain Fatigue" ],
    "Hackle-Lo Leaf": [ "Restore Fatigue", "Restore Luck", "Water Breathing", "Paralyze" ],
    "Heartwood": [ "Restore Magicka", "Fortify Agility", "Drain Strength", "Weakness to Fire" ],
    "Heather": [ "Restore Personality", "Feather", "Drain Personality", "Drain Speed" ],
    "Holly Berries": [ "Frost Shield", "Resist Frost", "Weakness to Fire", "Frost Damage" ],
    "Horker Tusk": [ "Detect Animal", "Fortify Maximum Magicka", "Fortify Intelligence", "Drain Alteration" ],
    "Horn Lily Bulb": [ "Restore Endurance", "Restore Strength", "Resist Paralysis", "Drain Health" ],
    "Hound Meat": [ "Restore Fatigue", "Detect Enchantment", "Fortify Fatigue", "Reflect" ],
    "Human Flesh": [ "Fortify Health", "Drain Intelligence", "Drain Personality" ],
    "Hypha Facia": [ "Detect Enchantment", "Drain Fatigue", "Drain Agility", "Drain Luck" ],
    "Kagouti Hide": [ "Night Eye", "Fortify Speed", "Resist Common Disease", "Drain Fatigue" ],
    "Kresh Fiber": [ "Restore Luck", "Fortify Personality", "Drain Magicka", "Drain Speed" ],
    "Kwama Cuttle": [ "Water Breathing", "Water Walking", "Resist Poison", "Drain Fatigue" ],
    "Large Corprusmeat Hunk": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ],
    "Large Kwama Egg": [ "Restore Fatigue", "Frost Shield", "Fortify Health", "Paralyze" ],
    "Large Wrapped Corprusmeat": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ],
    "Lloramor Spines": [ "Invisibility", "Detect Enchantment", "Spell Absorption", "Poison" ],
    "Luminous Russula": [ "Water Breathing", "Drain Fatigue", "Poison" ],
    "Marshmerrow": [ "Restore Health", "Detect Enchantment", "Drain Fatigue", "Drain Willpower" ],
    "Meadow Rye": [ "Restore Speed", "Fortify Speed", "Drain Speed", "Damage Health" ],
    "Medium Corprusmeat Hunk": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ],
    "Medium Wrapped Corprusmeat": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ],
    "Meteor Slime": [ "Restore Willpower", "Cure Blight Disease", "Cure Poison", "Fortify Willpower" ],
    "Moon Sugar": [ "Dispel", "Fortify Speed", "Drain Endurance", "Drain Luck" ],
    "Muck": [ "Detect Key", "Cure Common Disease", "Drain Intelligence", "Drain Personality" ],
    "Netch Leather": [ "Cure Paralyzation", "Fortify Endurance", "Fortify Intelligence", "Drain Personality" ],
    "Nirthfly Stalks": [ "Restore Speed", "Fortify Speed", "Drain Speed", "Damage Health" ],
    "Noble Sedge Flowers": [ "Restore Agility", "Fortify Agility", "Poison", "Damage Health" ],
    "Pearl": [ "Water Breathing", "Dispel", "Resist Common Disease", "Drain Agility" ],
    "Poison": [ "Weakness to Poison", "Poison", "Damage Health", "Damage Fatigue" ],
    "Racer Plumes": [ "Levitate", "Drain Willpower" ],
    "Rat Meat": [ "Cure Poison", "Resist Poison", "Drain Magicka", "Paralyze" ],
    "Raw Ebony": [ "Restore Speed", "Frost Shield", "Cure Poison", "Drain Agility" ],
    "Raw Glass": [ "Fire Shield", "Drain Intelligence", "Drain Speed", "Drain Strength" ],
    "Raw Stalhrim": [ "Restore Health", "Resist Frost", "Paralyze", "Frost Damage" ],
    "Red Lichen": [ "Light", "Cure Common Disease", "Drain Magicka", "Drain Speed" ],
    "Resin": [ "Restore Health", "Restore Speed", "Resist Common Disease", "Burden" ],
    "Roobrush": [ "Cure Poison", "Fortify Agility", "Drain Health", "Drain Willpower" ],
    "Ruby": [ "Restore Intelligence", "Feather", "Drain Health", "Drain Agility" ],
    "Saltrice": [ "Restore Fatigue", "Restore Health", "Fortify Magicka", "Drain Strength" ],
    "Scales": [ "Restore Endurance", "Swift Swim", "Water Walking", "Drain Personality" ],
    "Scamp Skin": [ "Restore Personality", "Restore Strength", "Cure Paralyzation", "Drain Magicka" ],
    "Scathecraw": [ "Restore Willpower", "Cure Poison", "Drain Health", "Drain Strength" ],
    "Scrap Metal": [ "Restore Intelligence", "Lightning Shield", "Resist Shock", "Drain Health" ],
    "Scrib Cabbage": [ "Restore Agility", "Fortify Agility", "Drain Intelligence", "Damage Health" ],
    "Scrib Jelly": [ "Restore Willpower", "Cure Blight Disease", "Cure Poison", "Fortify Willpower" ],
    "Scrib Jerky": [ "Restore Fatigue", "Swift Swim", "Fortify Fatigue", "Burden" ],
    "Scuttle": [ "Restore Fatigue", "Feather", "Telekinesis", "Fortify Fatigue" ],
    "Shalk Resin": [ "Fortify Health", "Fortify Speed", "Drain Fatigue", "Drain Personality" ],
    "Sload Soap": [ "Restore Agility", "Fire Shield", "Fortify Agility", "Drain Personality" ],
    "Small Corprusmeat Hunk": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ],
    "Small Kwama Egg": [ "Restore Fatigue" ],
    "Small Wrapped Corprusmeat": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ],
    "Snow Bear Pelt": [ "Night Eye", "Fortify Speed", "Resist Common Disease", "Drain Fatigue" ],
    "Snow Wolf Pelt": [ "Night Eye", "Fortify Speed", "Resist Common Disease", "Drain Fatigue" ],
    "Spore Pod": [ "Detect Key", "Drain Fatigue", "Drain Strength", "Paralyze" ],
    "Stoneflower Petals": [ "Restore Strength", "Fortify Magicka", "Fortify Personality", "Drain Luck" ],
    "Sweetpulp": [ "Restore Health", "Levitate", "Resist Paralysis", "Paralyze" ],
    "Timsa-Come-By flowers": [ "Restore Endurance", "Dispel", "Resist Paralysis", "Drain Magicka" ],
    "Trama Root": [ "Restore Willpower", "Levitate", "Drain Magicka", "Drain Speed" ],
    "Vampire Dust": [ "Fortify Health", "Fortify Strength", "Spell Absorption", "Vampirism" ],
    "Violet Coprinus": [ "Water Walking", "Drain Fatigue", "Poison" ],
    "Void Salts": [ "Restore Magicka", "Spell Absorption", "Drain Endurance", "Paralyze" ],
    "Wickwheat": [ "Restore Health", "Fortify Willpower", "Paralyze", "Damage Intelligence" ],
    "Willow Anther": [ "Frost Shield", "Cure Common Disease", "Cure Paralyzation", "Drain Personality" ],
    "Wolf Pelt": [ "Night Eye", "Fortify Speed", "Resist Common Disease", "Drain Fatigue" ],
    "Wolfsbane Petals": [ "Restore Intelligence", "Invisibility", "Drain Magicka", "Drain Endurance" ],
    "Wrapped Corprusmeat Hunk": [ "Drain Fatigue", "Drain Health", "Drain Magicka" ]
};
